
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: Image
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_Image[78] = {
    // ∙∙∙∙∙∙∙∙∙∙███∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙█████∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙███∙██∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙███∙████∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙███∙∙███∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙███∙∙███∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙████∙∙███∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙██∙∙∙∙███∙∙∙∙∙∙
    // █████████∙∙∙███∙∙∙∙∙∙∙
    // ████████∙∙∙██████████∙
    // ███████∙∙∙████████████
    // ██████∙∙∙∙████∙∙∙∙∙∙██
    // ██████∙∙∙∙∙∙██∙∙∙∙∙∙██
    // ██████∙∙∙∙∙∙██████████
    // ██████∙∙∙∙∙███████████
    // ██████∙∙∙∙∙██∙∙∙∙∙∙∙██
    // ██████∙∙∙∙∙███████████
    // ██████∙∙∙∙∙∙██████████
    // ██████∙∙∙∙∙███████████
    // ██████∙∙∙∙∙██∙∙∙∙∙∙∙██
    // ██████∙∙∙∙∙███████████
    // ██████∙∙∙∙∙∙█████████∙
    // ██████∙∙∙∙∙∙██∙∙∙∙███∙
    // ████████∙∙∙∙████∙███∙∙
    // ███████████████████∙∙∙
    // ██████∙███████████∙∙∙∙
    0x00, 0x38, 0x00, 
    0x00, 0x7c, 0x00, 
    0x00, 0xec, 0x00, 
    0x00, 0xef, 0x00, 
    0x00, 0xe7, 0x00, 
    0x00, 0xe7, 0x00, 
    0x01, 0xe7, 0x00, 
    0x01, 0x87, 0x00, 
    0xff, 0x8e, 0x00, 
    0xff, 0x1f, 0xf8, 
    0xfe, 0x3f, 0xfc, 
    0xfc, 0x3c, 0x0c, 
    0xfc, 0x0c, 0x0c, 
    0xfc, 0x0f, 0xfc, 
    0xfc, 0x1f, 0xfc, 
    0xfc, 0x18, 0x0c, 
    0xfc, 0x1f, 0xfc, 
    0xfc, 0x0f, 0xfc, 
    0xfc, 0x1f, 0xfc, 
    0xfc, 0x18, 0x0c, 
    0xfc, 0x1f, 0xfc, 
    0xfc, 0x0f, 0xf8, 
    0xfc, 0x0c, 0x38, 
    0xff, 0x0f, 0x70, 
    0xff, 0xff, 0xe0, 
    0xfd, 0xff, 0xc0
};
const tImage Image = { image_data_Image, 22, 26,
    8 };

