
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: Image
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_Image[87] = {
    // ∙∙∙∙∙∙∙∙∙∙∙████∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙████∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙██████∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙██∙∙███∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙██∙∙∙██∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙██∙∙∙██∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙██∙∙∙██∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙████∙∙∙██∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙██∙∙∙∙∙██∙∙∙∙∙∙∙
    // ██████∙██∙∙∙∙∙██∙∙∙∙∙∙∙∙
    // █████████∙∙∙███████████∙
    // ████████∙∙∙█████████████
    // ███∙██∙∙∙∙∙██∙██∙∙∙∙∙∙██
    // ███∙██∙∙∙∙∙██∙██∙∙∙∙∙∙██
    // ██████∙∙∙∙∙∙∙∙██████████
    // ██████∙∙∙∙∙∙∙∙██████████
    // ██████∙∙∙∙∙∙███∙∙∙∙∙∙∙██
    // ██████∙∙∙∙∙∙███∙∙∙∙∙∙∙██
    // ██████∙∙∙∙∙∙████████████
    // ██████∙∙∙∙∙∙∙∙██████████
    // ██████∙∙∙∙∙∙████████████
    // ██████∙∙∙∙∙∙███∙∙∙∙∙∙∙██
    // ██████∙∙∙∙∙∙███∙∙∙∙∙∙∙██
    // ██████∙∙∙∙∙∙∙∙█████████∙
    // ██████∙∙∙∙∙∙∙∙█████████∙
    // █████████∙∙∙∙∙███∙∙████∙
    // █████████∙∙∙∙∙∙██∙∙███∙∙
    // █████████████████████∙∙∙
    // ██████∙∙████████████∙∙∙∙
    0x00, 0x1e, 0x00, 
    0x00, 0x1e, 0x00, 
    0x00, 0x3f, 0x00, 
    0x00, 0x33, 0x80, 
    0x00, 0x31, 0x80, 
    0x00, 0x31, 0x80, 
    0x00, 0x31, 0x80, 
    0x00, 0xf1, 0x80, 
    0x00, 0xc1, 0x80, 
    0xfd, 0x83, 0x00, 
    0xff, 0x8f, 0xfe, 
    0xff, 0x1f, 0xff, 
    0xec, 0x1b, 0x03, 
    0xec, 0x1b, 0x03, 
    0xfc, 0x03, 0xff, 
    0xfc, 0x03, 0xff, 
    0xfc, 0x0e, 0x03, 
    0xfc, 0x0e, 0x03, 
    0xfc, 0x0f, 0xff, 
    0xfc, 0x03, 0xff, 
    0xfc, 0x0f, 0xff, 
    0xfc, 0x0e, 0x03, 
    0xfc, 0x0e, 0x03, 
    0xfc, 0x03, 0xfe, 
    0xfc, 0x03, 0xfe, 
    0xff, 0x83, 0x9e, 
    0xff, 0x81, 0x9c, 
    0xff, 0xff, 0xf8, 
    0xfc, 0xff, 0xf0
};
const tImage Image = { image_data_Image, 24, 29,
    8 };

