
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: Image
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Edge 0
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_Image[63] = {
    // ∙∙███∙∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙∙███∙∙∙∙∙∙∙∙∙∙∙███∙∙
    // ███████∙∙∙∙∙∙∙███████
    // ███████∙∙∙∙∙∙∙███████
    // █████████∙∙∙█████████
    // ∙∙███████∙∙∙███████∙∙
    // ∙∙█████████████████∙∙
    // ∙∙∙∙█████████████∙∙∙∙
    // ∙∙∙∙█████████████∙∙∙∙
    // ∙∙∙∙∙∙█████████∙∙∙∙∙∙
    // ∙∙∙∙∙∙█████████∙∙∙∙∙∙
    // ∙∙∙∙∙∙█████████∙∙∙∙∙∙
    // ∙∙∙∙█████████████∙∙∙∙
    // ∙∙∙∙█████████████∙∙∙∙
    // ∙∙█████████████████∙∙
    // ∙∙███████∙∙∙███████∙∙
    // ████████∙∙∙∙█████████
    // ███████∙∙∙∙∙∙∙███████
    // ██████∙∙∙∙∙∙∙∙███████
    // ∙∙███∙∙∙∙∙∙∙∙∙∙∙███∙∙
    // ∙∙██∙∙∙∙∙∙∙∙∙∙∙∙███∙∙
    0x38, 0x00, 0xe0, 
    0x38, 0x00, 0xe0, 
    0xfe, 0x03, 0xf8, 
    0xfe, 0x03, 0xf8, 
    0xff, 0x8f, 0xf8, 
    0x3f, 0x8f, 0xe0, 
    0x3f, 0xff, 0xe0, 
    0x0f, 0xff, 0x80, 
    0x0f, 0xff, 0x80, 
    0x03, 0xfe, 0x00, 
    0x03, 0xfe, 0x00, 
    0x03, 0xfe, 0x00, 
    0x0f, 0xff, 0x80, 
    0x0f, 0xff, 0x80, 
    0x3f, 0xff, 0xe0, 
    0x3f, 0x8f, 0xe0, 
    0xff, 0x0f, 0xf8, 
    0xfe, 0x03, 0xf8, 
    0xfc, 0x03, 0xf8, 
    0x38, 0x00, 0xe0, 
    0x30, 0x00, 0xe0
};
const tImage Image = { image_data_Image, 21, 21,
    8 };

